# Generated by Django 6.0 on 2025-12-29 08:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Mobile Number')),
                ('address', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand (e.g. Samsung)')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model Name')),
                ('imei', models.CharField(max_length=15, unique=True, verbose_name='IMEI Number')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True, verbose_name='In Stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Final Deal Price')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Paid Now')),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BAJAJ', 'Bajaj Finance'), ('ONLINE', 'UPI / Online')], default='CASH', max_length=10)),
                ('transaction_id', models.CharField(blank=True, help_text='Bajaj File No or UPI ID', max_length=100, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_details', to='core.product')),
            ],
        ),
    ]
