# Generated by Django 6.0 on 2025-12-29 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_type', models.CharField(choices=[('Rent', 'Rent'), ('Electricity', 'Electricity'), ('Tea/Food', 'Tea & Snacks'), ('Others', 'Others')], max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
