# Generated by Django 6.0 on 2026-01-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_invoice_transaction_id_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10, unique=True, verbose_name='Mobile Number'),
        ),
    ]
